### ISSUE TITLE
Ore Flowers StackOverflow

### ISSUE THREAD

**Issue by jeffpengMC** [reteo/Survival-Industry#74]
Implementing a server instance of SI I got this repeatedly, eventually resulting in a crashed server:

java.lang.StackOverflowError
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_72]
        at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500) ~[?:1.8.0_72]
        at cpw.mods.fml.common.eventhandler.EventBus.handleException(EventBus.java:154) ~[EventBus.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:145) ~[EventBus.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at com.draco18s.flowers.util.OreCountGenerator.generate(OreCountGenerator.java:35) ~[OreCountGenerator.class:?]
        at com.draco18s.flowers.util.OreDataHooks.readData(OreDataHooks.java:146) ~[OreDataHooks.class:?]
        at com.draco18s.flowers.OresEventHandler.chunkLoad(OresEventHandler.java:61) ~[OresEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_725_OresEventHandler_chunkLoad_Load.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at com.draco18s.flowers.util.OreCountGenerator.generate(OreCountGenerator.java:35) ~[OreCountGenerator.class:?]
        at com.draco18s.flowers.util.OreDataHooks.readData(OreDataHooks.java:146) ~[OreDataHooks.class:?]
        at com.draco18s.flowers.OresEventHandler.chunkLoad(OresEventHandler.java:61) ~[OresEventHandler.class:?]

**Comment by jeffpengMC** [comment]
Apparently this only happens when introducing OreFlowers to a world that has already generated.
